### PR TITLE
Add todayonline.com handler

### PR DESCRIPTION
**Pull request by yleong**
Test: https://www.reddit.com/r/rsgretrivr/comments/ac5q0z/feeling_less_productive_blame_it_on_the_air_nus/
https://www.reddit.com/r/rsgretrivr/comments/ac5stp/activist_jolovan_wham_found_guilty_of_organising/

### CODE REVIEW

**Comment by fterh** [comment]
Hey @yleong, thanks so much for helping out, I really appreciate it!

Just a heads up, I've been swamped these few days, and I'm flying to HK tomorrow for about a week, so I'll either be very slow to respond/merge or offline completely until next weekend. But I'll definitely get around to it.

**Comment by yleong** [comment]
No problem and thanks for the heads up.

**Comment by fterh** [comment]
@yleong 
Can I confirm with you if beautifulsoup4 is a required package for this? I had a look at your branch, your pipfile does not list bs4 but your pipfile.lock does.

**Comment by yleong** [comment]
Yes it is needed in order to extract the articleid. I had totally forgotten to update the pipfile, sorry.

**Pull request merged**
