### PR TITLE
Add handlers for businesstimes.com.sg, yahoo.com, tnp.sg

### PR DESCRIPTION
**Pull request by changhuapeng**
**Tests for businesstimes.com.sg**
- https://www.reddit.com/r/rsgretrivr/comments/auxo9v/companies_struggle_to_meet_customer_expectations/ehbmk4z/
- https://www.reddit.com/r/rsgretrivr/comments/auxw90/irrelevance_thy_name_is_telco_bundling/ehbmazf/
- https://www.reddit.com/r/rsgretrivr/comments/auxywq/distillers_revive_old_favourite_maryland_rye/ehbmay1/
- https://www.reddit.com/r/rsgretrivr/comments/av0fvy/uber_in_talks_to_sell_india_fooddelivery_business/ehboruo/

**Tests for yahoo.com**
- https://www.reddit.com/r/rsgretrivr/comments/av0ta5/lorry_driver_in_viral_video_of_altercation_with/ehbt6fp/
- https://www.reddit.com/r/rsgretrivr/comments/av0xdi/manafort_sentencing_hearing_rescheduled_to_march/ehbt6d8/
- https://www.reddit.com/r/rsgretrivr/comments/av11g6/exclusive_despite_sanctions_russian_tanker/ehbt6ac/
- https://www.reddit.com/r/rsgretrivr/comments/av15nr/michael_cohen_to_accuse_trump_of_criminal/ehbt66w/

**Tests for tnp.sg**
- https://www.reddit.com/r/rsgretrivr/comments/av1ek3/cyclist_punches_lorry_driver_and_rides_off_after/ehbywd1/
- https://www.reddit.com/r/rsgretrivr/comments/av1iy6/give_solskjaer_the_fulltime_job_or_fans_will/ehbywb2/
- https://www.reddit.com/r/rsgretrivr/comments/av1nef/pretty_please_get_fresh_with_latest_spring/ehbyw70/
- https://www.reddit.com/r/rsgretrivr/comments/av1suk/oscars_not_so_white_academy_awards_winners_see/ehbyw4n/

### CODE REVIEW

**Comment by xlanor** [comment]
Thank you for contributing!

I  have requested a review from the other collaborators and will review the changes shortly myself once I get into the qork

**Comment by fterh** [comment]
Looks alright to me, but why are single quotes and double quotes used interchangeably? Let's keep it consistent and use double quotes? (e.g. line 32 `for line in article_soup.select('div.article-body > p'):` of `BusinesstimesHandler/__init__.py`).

@xlanor After this is fixed and merged into develop, I think I can release v0.5.0-beta :)

**Comment by changhuapeng** [comment]
@fterh That was a lapse on my part when I copied that line from BeautifulSoup documentation. I will fix them later once I have the time.

**Comment by xlanor** [comment]
> Looks alright to me, but why are single quotes and double quotes used interchangeably? Let's keep it consistent and use double quotes? (e.g. line 32 `for line in article_soup.select('div.article-body > p'):` of `BusinesstimesHandler/__init__.py`).
> 
> @xlanor After this is fixed and merged into develop, I think I can release v0.5.0-beta :)

Thanks for catching that, didn't notice.

Will merge in once the fix has been commited.

**Comment by changhuapeng** [comment]
Thanks for spotting the mistake! I've made the necessary changes.

On a side note, is it possible to adjust the anti-spam 10 minutes per submission limit on r/rsg-retrivr? So as to make the wait between test post submissions shorter.

**Comment by yleong** [comment]
Nice work! However, I think it's neater to fixup the `Update syntax..` commit so that we still get the 3 self-contained commits like before.

**Comment by changhuapeng** [comment]
@yleong Thanks for making me an Approved Submitter!

I'm not too sure if a forced-push to overwrite the branch is the appropriate way but I have fixed the pull request to 3 self-contained commits like before.

**Comment by yleong** [comment]
Yes, a force push is fine since it is your own branch.

**Pull request merged**
