### PR TITLE
updated readme. Added cnb.gov and theonlinecitizen.com. Moving to devel as requested

### PR DESCRIPTION
**Pull request by rickithadi**

### CODE REVIEW

**Comment by xlanor** [comment]
I spoke to @fterh - this PR will be put on hold until we can figure out a reliable way to test the scraping on the source.

Do you happen to have any source links to articles that were used?

**Comment by rickithadi** [comment]
Yes they are on the rsgretrivr sub. https://redd.it/amq7no as well as
https://redd.it/ampnv5

**Comment by yleong** [comment]
@rickithadi 
Thanks for providing the links to the working test cases on `r/rsgretrivr/`, they look good.

Before your PR can be merged, can you make the following changes:

1. Please remove `main_dev.db` from your commit. It is not useful to commit that unless you are also introducing a schema change or something like that.

2. Please split your adding of two websites and your improving of `README.md` into two separate commits. This will help with possible reverts or cherry-picks.

3. Please reword your commit messages to use present tense. This will help your commits be consistent with the existing ones:

```
:sneakpeek% git log --no-decorate --oneline | head                                                                 
29b39a4 Merge branch 'release-v0.4.0-beta'
cee43ef Update README.md
5f383c3 Bump to v0.4.0-beta
06ab6d1 Merge pull request #10 from yleong/yleong#6
1a2d2ed Add STHandler to handle both premium and non premium ST articles
6ab9455 Merge branch 'release-v0.3.0-beta'
8846a10 Merge branch 'release-v0.3.0-beta' into develop
726d22c Update README.md
257ec0e Bump to v0.3.0-beta
4835b0f Update README.md
```

**Comment by yleong** [comment]
@rickithadi 
A new release might be cut soon. Do you still have time to work on this and get it included in the upcoming release?

**Pull request closed without merging**
